create procedure sp_update_dim_cliente 
										@nrocliente int,
										@actividad nvarchar(50),
										@apellido nvarchar(50),
										@nombre nvarchar(50),
										@sexo nvarchar(50),
										@email nvarchar(40),
										@fechanac date,
										@nrocuentacliente bigint,
										@sectoreconomico nvarchar(20),
										@condicioniva nvarchar(10),
										@tipo nvarchar(1),
										@segmento nvarchar(20),
										@tipodocumento nvarchar(10),
										@nrodocumento nvarchar(8),
										@cuit nvarchar(13),
										@telefono nvarchar(10),
										@cuentacobro nvarchar(40),
										@situacionmorabanco int,
										@situacionmorasf int
as
	update dbo.Dim_Cliente 
	set 
		NroCliente = @nrocliente,
		Actividad = @actividad,
		Apellido = @apellido,
		Nombre = @nombre,
		Sexo = @sexo,
		Email = @email,
		FechaNacimiento = @fechanac,
		NroCuentaCliente = @nrocuentacliente,
		SectorEconomico = @sectoreconomico,
		CondicionIVA = @condicioniva,
		Tipo = @tipo,
		Segmento = @segmento,
		TipoDocumento = @tipodocumento,
		NroDocumento = @nrodocumento,
		Cuit = @cuit,
		Telefono = @telefono,
		CuentaCobro = @cuentacobro,
		SituacionMoraBanco = @situacionmorabanco,
		SituacionMoraSF = @situacionmorasf
	where NroDocumento = @nrodocumento and Cuit = @cuit